config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get '/dashboard', to: 'dashboard#index'
  get '/words', to:'words#index'
  
  resources :users do 
      member do 
          get 'followers', 'following'
          delete 'followes', 'following'
      end
  end 
  
  resources :sessions
  resources :categories
  
  Rails.application.routes.draw do 
  	namespace :admin do 
  		resources :users
  		resources :categories do 
        resources :words
      end
  	end

    resources :lessons do
      resources :lesson_words
    end 
  end

  resources :relationships, only: [:create, :destroy]


end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :action, polymorphic: true
  belongs_to :user 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :words, dependent: :destroy
	has_many :lessons, dependent: :destroy

	validates :title, presence: true, 
					  length:{ maximum: 50}

	validates :description, presence: true, 
					 		length:{ maximum: 150}
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :user
  belongs_to :category

  has_many :lesson_words, dependent: :destroy
  has_many :words, through: :lesson_words, dependent: :destroy
  has_many :words_answer, through: :lesson_words, dependent: :destroy

  has_many :activities, :as => :action, dependent: :destroy 

end

app/models/lesson_word.rb
class LessonWord < ApplicationRecord
  belongs_to :lesson
  belongs_to :word
  belongs_to :words_answer
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "User"

	has_many :activities, :as => :action, dependent: :destroy 
	
end

app/models/user.rb
class User < ApplicationRecord
	has_many :lessons,  dependent: :destroy

	has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
	has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

	has_many :following, through: :active_relationships, source: :followed, dependent: :destroy
	has_many :followers, through: :passive_relationships, dependent: :destroy

	has_many :lesson_words, through: :lessons, dependent: :destroy

	has_many :activities, dependent: :destroy

	before_save { self.email = email.downcase }
 	validates :name, presence: true, 
					 length:{ maximum: 50}
 	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
 	validates :email, presence: true,
					  length:{ maximum: 255},
					  format:{with: VALID_EMAIL_REGEX},
					  uniqueness: {case_sensitive: false} 

 	has_secure_password 

 	def follow(other_user)
		following << other_user

		relationship = active_relationships.find_by(followed: other_user)
		relationship.activities.create(user: self)
	end

	def following?(other_user)
		following.include? other_user
		
	end

	def unfollow(other_user)
		relationship = active_relationships.find_by(followed: other_user)
		relationship.activities.first.destroy

		following.delete(other_user)
	end
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :category
  has_many :words_answers, dependent: :destroy
  has_many :lesson_words, dependent: :destroy
  
  accepts_nested_attributes_for :words_answers

  validates :content, presence: true  

  validate :has_one_correct_answer

  def correct_answer
  	words_answers.each do |answer|
  		if answer.correct?
  			return answer.content
  		end
  	end 
  end

  private
	  def has_one_correct_answer
	   unless words_answers.collect { |i| i.correct? || nil  }.compact.count == 1
	      errors.add(:word_answers, "should have one correct answer")
	    end
	  end

  
end

app/models/words_answer.rb
class WordsAnswer < ApplicationRecord
  belongs_to :word
  has_many :lesson_words, dependent: :destroy

  validates :content, presence: true
  
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	before_action :require_login
	
	def index
		user = current_user
		@activities = user.activities
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :correct_user, only: [:edit, :update]
	before_action :require_login, except: [:new, :create]
	before_action :admin_user, only: :destroy


	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)

		if @user.save 
			flash[:success] = "Successfully saved"  
			redirect_to root_path
		else
			render 'new'

		end
	end

	def show
		user = User.find(params[:id])
		@activities = user.activities

		if logged_in?
			session[:user_id]
			@user = User.find(params[:id])
			
		else
			flash[:danger] = "You can't access that page"
			redirect_to root_url
		end
	end

	def edit
		@user = User.find(params[:id])
		
	end

	def update 
		@user = current_user

		if @user.update_attributes(user_params)
		 	flash[:success] = "Successfully updated" 
		 	redirect_to edit_user_url(@user)

		else
			render 'edit'

		end
	end

	def index
		@users = User.paginate(page: params[:page], per_page: 10)
	end

	def followers
		@user = User.find(params[:id])
		@title = "Followers"
		@users = @user.followers
		render 'show_follow'
	end


	def following
		@user = User.find(params[:id])
		@title = "Following"
		@users = @user.following
		render 'show_follow'
	end
	
	def destroy
		@user = User.find(params[:id])
		@user.destroy
			# flash[:success] = "User #{@user.name} has been removed."

		redirect_to users_url
	end


	private 
		def user_params
			params.require(:user).permit(:name, :email, :password, :password_confirmation)
		end

		def correct_user
			user = User.find(params[:id])
			unless current_user == user
				flash[:danger] = "Error."
				redirect_to root_url
				
			end
		end

		def admin_user
			unless current_user.admin?
				flash[:info] = "You are not allowed to do that"
				redirect_to users_url
			end
			
		end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
	before_action :require_login

	def index
		@lesson = current_user.lessons
		@lessonword = current_user.lesson_words
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/lesson_words_helper.rb
module LessonWordsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
		session[:user_id] = user.id 	
	end

	def current_user 
		User.find_by(id: session[:user_id])
	end

	def log_out
		session.delete(:user_id)
	end

	def logged_in?
		!current_user.nil?
	end

	def current_user?(user)
		current_user == user
		
	end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user, size=80) 
		gravatar_id = Digest::MD5::hexdigest(user.email)
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url)
	end
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/dashboard/index.html.erb
<div class="container container-small"">
	<div class="row">
		<div class="col-sm-4">
			<div class="panel panel-default">
				<div class="panel-heading">
					<span class="heading">User Information</span>
				</div>

				<div class="panel-body">
					<div class="user_info text-center">
						<div class="avatar">
							<%= gravatar_for(current_user)%>
						</div>
						
						<h3><%= current_user.name %></h3>

						<div class="text-gray mb-15"">
							<%= current_user.email %>
						</div>

						<%= link_to "Update profile", edit_user_path(current_user), class: "btn btn-xs btn-warning" %>
						<% @user ||= current_user %>
					</div>
				</div>
			</div>	
			
			<div class="panel panel-default">
				<div class="panel-heading">
					<span class="heading">User Stats</span>
				</div>

				<div class="panel-body">
					<div class="learned_info text-center">
						<div class="btn-group btn-group-justified">
							<%= link_to words_path do %>
								<p><strong>Word learned <%= @user.lesson_words.count %></strong><p>
							<% end %>
						</div>

						<div class="btn-group btn-group-justified mt-20">
							<div class="btn btn-default">
								<%= link_to followers_user_path(@user) do %>
									<strong><%= @user.followers.count %></strong> followers
								<% end %>
							</div>
							
							<div class="btn btn-default">
								<%= link_to following_user_path(@user) do %>
									<strong><%= @user.following.count %></strong> following
								<% end %>
							</div>

						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="col-sm-8">
			<div class="panel panel-default activity-feed">
				<div class="panel-heading">
					<span class="heading">Activity Feeds</span>
				</div>

				<div class="panel-body">
					<% @activities.each do |activity| %>
						<div class="media">
							<div class="media-left media-middle">
								<%= gravatar_for(activity.user, 50)%>
							</div>
							
							<div class="media-body media-middle">
								<% if activity.action_type == "Relationship" %>
									<div>
										<%= link_to activity.user.name, user_path(activity.user.id) %> followed <%= link_to activity.action.followed.name, user_path(activity.action.followed.id) %>
										<p><small><%= time_ago_in_words(activity.created_at) %> ago</small></p>
									</div>
								<% else %>
									<div>
										<%= link_to activity.user.name, user_path(activity.user.id) %> learned <%= link_to activity.action.category.title, lesson_lesson_words_path(activity.action.id) %>
										<p><small><%= time_ago_in_words(activity.created_at) %> ago</small></p>
									</div>
								<% end %>
							</div>
						</div>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>