config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get '/dashboard', to: 'dashboard#index'
  get '/words', to:'words#index'
  
  resources :users do 
      member do 
          get 'followers', 'following'
          delete 'followes', 'following'
      end
  end 
  
  resources :sessions
  resources :categories
  
  Rails.application.routes.draw do 
  	namespace :admin do 
  		resources :users
  		resources :categories do 
        resources :words
      end
  	end

    resources :lessons do
      resources :lesson_words
    end 
  end

  resources :relationships, only: [:create, :destroy]


end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :category
  has_many :words_answers, dependent: :destroy
  has_many :lesson_words, dependent: :destroy
  
  accepts_nested_attributes_for :words_answers

  validates :content, presence: true  

  validate :has_one_correct_answer

  def correct_answer
  	words_answers.each do |answer|
  		if answer.correct?
  			return answer.content
  		end
  	end 
  end

  private
	  def has_one_correct_answer
	   unless words_answers.collect { |i| i.correct? || nil  }.compact.count == 1
	      errors.add(:word_answers, "should have one correct answer")
	    end
	  end

  
end

app/controllers/admin/words_controller.rb
class Admin::WordsController < ApplicationController
	before_action :require_login
	before_action :admin_user
	def new
		@category = Category.find(params[:category_id])
		@word = @category.words.build
		3.times { @word.words_answers.build }
	end

	def create
		@category = Category.find(params[:category_id])
		@word = @category.words.build(word_params)

		if @word.save 
			flash[:success] = "Successfully saved"  
			redirect_to new_admin_category_word_path
		else
			render 'new'
		end
	end

	def index
		@category = Category.find(params[:category_id])
		@word = @category.words
	end

	def edit
		@category = Category.find(params[:category_id])
		@word = Word.find(params[:id])

	end

	def update
		@word = Word.find(params[:id])
		@category = Category.find(params[:category_id])

		if @word.update_attributes(word_params)
			flash[:success] = "Successfully updated" 
			redirect_to admin_category_words_path
		else
			render 'edit'
			
		end
	end

	def destroy
		@category = Category.find(params[:category_id])
		@word = Word.find(params[:id])
		@word.destroy
			flash[:success] = "Successfully all delete!"

		redirect_to admin_category_words_path(@category)
		
	end
	


	private
		def word_params
			params.require(:word).permit(:content, words_answers_attributes: [:id,:content,:correct])
		end
		
		def admin_user
			unless current_user.admin?
				flash[:info] = "You are not allowed to do that"
				redirect_to users_url
			end
		end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
	before_action :require_login

	def index
		@lesson = current_user.lessons
		@lessonword = current_user.lesson_words
	end

end

app/helpers/admin/words_helper.rb
module Admin::WordsHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/admin/words/edit.html.erb
<div class="container container-small">
	<div class="panel">
		<div class= "panel-heading">
			<div class="row">
				<div class="col-sm-6">
					<span><strong>Admin Words</strong></span>
				</div>

				<div class="col-sm-6 text-right">
					<%#= link_to "BACK", admin_category_words_path(category.id) %>
				</div>
			</div>
		</div>

		<div class="panel-body">

			<div class="row">
				<div class="col-md-8 col-center">
					<%= form_for ([:admin, @category, @word]) do |f| %>
						<% if @word.errors.any? %>
							<div class="alert alert-danger">
								This form contains <%= pluralize(@word.errors.count, "error") %>
							</div>
							<ul>
								<% @word.errors.full_messages.each do |msg| %>
								<li><%= msg %></li>
								<% end %>
							</ul>
						<% end %>

						<div class="form-group row">
								<div class="col-sm-2">
									<%= f.label :content,"Word" %>
								</div>
								
								<div class="col-sm-10">
									<%= f.text_field :content, class:'form-control' %>
								</div>
						</div>

						<div class="form-group row">
							<%=f .fields_for :words_answers do |field| %>
								<div class="col-sm-3">
									<%= field.label :content,"Choices" %>
								</div>
								
								<div class="col-sm-9">
									<%= field.text_field :content, class:'form-control' %>
									<%= field.check_box :correct %>
									<%= field.label :correct, "Correct" %>
								</div>
							<% end %>
						</div>
	
						<div class="form-group">
							<%= f.submit class: 'btn btn-success form-control'%>
						</div>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/admin/words/index.html.erb
<div class="container container-small">
	<div class="panel">
		<div class= "panel-heading">
			<div class="row">
				<div class="col-sm-6">
					<span><strong>Admin Word Show Page</strong></span>
				</div>

				<div class="col-sm-6 text-right">
					<%= link_to "ADD WORD", new_admin_category_word_path(@category), class: "btn btn-success"%>
					<%= link_to "BACK", admin_categories_path, class: "btn"%>
				</div>
			</div>
		</div>

		<table class="table">
			<tbody>
				<tr>
					<th>Word</th>
					<th>Answer</th>
					<th>Action</th>
				</tr>
			
				<% @word.each do |word| %>
					<tr>
						<td><%= word.content %></td>
						<td><%= word.correct_answer %></td>
						<td><%= link_to "Edit", edit_admin_category_word_path(@category, word), class: "btn btn-xs btn-warning" %>
							<%= link_to "Delete", admin_category_word_path(@category, word),method: :delete, class: "btn btn-xs btn-light", data:{confirm: "Are you sure?"} %>
						</td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/admin/words/new.html.erb
<div class="container container-small">
	<div class="panel">
		<div class= "panel-heading">
			<div class="row">
				<div class="col-sm-6">
					<span><strong>Create Word Page</strong></span>
				</div>

				<div class="col-sm-6 text-right">
					<%#= link_to "BACK", admin_category_words_path(category.id) %>
				</div>
			</div>
		</div>

		<div class="panel-body">

			<div class="row">
				<div class="col-md-8 col-center">
					<%= form_for ([:admin, @category, @word]) do |f| %>
						<% if @word.errors.any? %>
							<div class="alert alert-danger">
								This form contains <%= pluralize(@word.errors.count, "error") %>
							</div>
							<ul>
								<% @word.errors.full_messages.each do |msg| %>
								<li><%= msg %></li>
								<% end %>
							</ul>
						<% end %>

						<div class="form-group row">
								<div class="col-sm-2">
									<%= f.label :content,"Word" %>
								</div>
								
								<div class="col-sm-10">
									<%= f.text_field :content, class:'form-control' %>
								</div>
						</div>

						<div class="form-group row">
							<%= f.fields_for :words_answers do |field| %>
								<div class="col-sm-3">
									<%= field.label :content,"Choices" %>
								</div>
								
								<div class="col-sm-9">
									<%= field.text_field :content, class:'form-control' %>
									<%= field.check_box :correct %>
									<%= field.label :correct, "Correct" %>
								</div>
							<% end %>
						</div>
	
						<div class="form-group">
							<%= f.submit class: 'btn btn-success form-control'%>
						</div>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>