config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get '/dashboard', to: 'dashboard#index'
  get '/words', to:'words#index'
  
  resources :users do 
      member do 
          get 'followers', 'following'
          delete 'followes', 'following'
      end
  end 
  
  resources :sessions
  resources :categories
  
  Rails.application.routes.draw do 
  	namespace :admin do 
  		resources :users
  		resources :categories do 
        resources :words
      end
  	end

    resources :lessons do
      resources :lesson_words
    end 
  end

  resources :relationships, only: [:create, :destroy]


end

app/models/category.rb
class Category < ApplicationRecord
	has_many :words, dependent: :destroy
	has_many :lessons, dependent: :destroy

	validates :title, presence: true, 
					  length:{ maximum: 50}

	validates :description, presence: true, 
					 		length:{ maximum: 150}
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
	before_action :require_login
	before_action :admin_user

	def index
		@categories = Category.all
	end

	def new
		@category = Category.new
	end

	def create
		@category = Category.new(category_params)
		if @category.save 
			flash[:success] = "Successfully saved"  
			redirect_to new_admin_category_path
		else
			render 'new'

		end
	end

	def edit
		@category = Category.find(params[:id])
		
	end

	def update
		@category = Category.find(params[:id])

		if @category.update_attributes(category_params)
			flash[:success] = "Successfully updated" 
			redirect_to edit_admin_category_path(@category)
		else
			render 'edit'
			
		end
		
	end

	def destroy
		@category = Category.find(params[:id])
		@category.destroy
			flash[:success] = "Successfully all delete!"

		redirect_to admin_categories_path
	end


	private
		def category_params
			params.require(:category).permit(:title, :description)
		end

		def admin_user
			unless current_user.admin?
				flash[:info] = "You are not allowed to do that"
				redirect_to users_url
			end
			
		end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_action :require_login
	
	def index
		@categories = Category.all
	end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/index.html.erb
<div class="container container-small">
	<h2>Categories</h2>
	<div class="row object-list">
		<% @categories.each do |category| %>
		<div class="col-sm-6">
			<section class= "col-sm-12">
				<div class="detail">
					<h2><%= category.title %></h2>
					<p><%= category.description %></p>
				</div>
				
				<div class="btn-wrapper text-right">
					<% if lesson = current_user.lessons.find_by(category_id: category.id) %>
						<%= link_to "Already Learned",lesson_lesson_words_path(lesson.id), class: 'btn btn-defalt' %>
					<% else %>
						<%= form_for :lesson, url: lessons_path do |f|%>
							<%= f.hidden_field :category_id, value: category.id %>
							<%= f.submit "LEARN", class: 'btn btn-primary'%>
						<% end %>
					<% end %>
				</div>
				
			</section>
		</div>
		<% end %>
	</div>
</div>